{{ config(materialized='view') }}

SELECT
  -- Primary identifiers
  CAST(FULL_NAME AS STRING) AS CUSTOMER_NAME,
  
  -- Names and descriptive fields
  CAST(EMAIL AS STRING) AS EMAIL,
  CAST(FIRST_NAME AS STRING) AS FIRST_NAME,
  CAST(LAST_NAME AS STRING) AS LAST_NAME,
  CAST(ADDRESS_COMPANY AS STRING) AS STREET_ADDRESS,
  CAST(ADDRESS_CITY AS STRING) AS CITY,
  CAST(ADDRESS_PROVINCE AS STRING) AS PROVINCE,
  CAST(ADDRESS_ZIP AS STRING) AS ZIP,
  CAST(PHONE AS STRING) AS PHONE

FROM {{ source('raw_data', 'customers') }}
