{{ config(materialized='table') }}

with orders as (
    select
        ORDER_DATE,
        YEAR(ORDER_DATE) AS ORDER_YEAR,
        MONTH(ORDER_DATE) AS ORDER_MONTH,
        TO_CHAR(ORDER_DATE, 'Month') AS ORDER_MONTHNAME,
        CONCAT(ORDER_MONTHNAME, '-', ORDER_YEAR) AS ORDER_MONTH_YEAR,
        QUANTITY,
        LINE_TOTAL AS SALES_AMOUNT
    from {{ ref('int_orders') }}
)

SELECT
    ROW_NUMBER() OVER (ORDER BY ORDER_YEAR, ORDER_MONTH) AS ROW_NUMBER,
    ORDER_MONTH_YEAR,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM orders
GROUP BY ORDER_YEAR, ORDER_MONTH, ORDER_MONTH_YEAR