models:
  - name: dim_accounts
    description: "Dimension table containing key information about customer accounts."
    columns:
      - name: account_id
        data_type: text
        description: "Uniique identifier for each customer account."
        tests:
          - unique
          - not_null

      - name: account
        data_type: text
        description: "Name of the customer account or organization."
        tests:
          - values_in_another_model:
              arguments:
                ref_model: ref('stg_sales_pipeline')
                ref_column: account

      - name: sector
        data_type: text
        description: "Industry or business sector of the customer account."

  - name: dim_calendar
    description: "Dimension table representing the calendar dates for time-based analysis."
    columns:
      - name: date
        data_type: date
        description: "Unique date value representing each day in the calendar."

      - name: year
        data_type: integer
        description: "Calendar year extracted from the date."

      - name: quarter
        data_type: integer
        description: "Calendar quarter (1-4) extracted from the date."

      - name: week_of_quarter
        data_type: double precision
        description: "Week number within the quarter for the given date, useful for granular trend analysis."

  - name: dim_products
    description: "Dimension table containing details about products offered."
    columns:
      - name: product_id
        data_type: text
        description: "Uniique identifier for each product."
        tests:
          - unique
          - not_null

      - name: product
        data_type: text
        description: "Name of the product offered."
        tests:
          - values_in_another_model:
              arguments:
                ref_model: ref('stg_sales_pipeline')
                ref_column: product

      - name: series
        data_type: text
        description: "Product line or series to which the product belongs."

      - name: sales_price
        data_type: numeric
        description: "Standard or listed sales price of the product."

  - name: dim_sales_teams
    description: "Dimension table containing information about sales agents and their teams."
    columns:
      - name: sales_agent_id
        data_type: text
        description: "Uniique identifier for each sales agent."
        tests:
          - unique
          - not_null

      - name: sales_agent
        data_type: text
        description: "Full name of the sales agent responsible for sales."
        tests:
          - values_in_another_model:
              arguments:
                ref_model: ref('stg_sales_pipeline')
                ref_column: sales_agent

      - name: manager
        data_type: text
        description: "Name of the manager overseeing the sales agent."

  - name: fact_sales_pipeline
    description: "Fact table capturing sales opportunities across the pipeline and their associated metrics."
    columns:
      - name: opportunity_id
        data_type: text
        description: "Unique indentifier for each sales opportunity or deal."
        tests:
          - unique
          - not_null

      - name: sales_agent_id
        data_type: text
        description: "Same value as sales_agent_id in the dim_sales_teams table, linking to the responsible sales agent."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_sales_teams')
                field: sales_agent_id

      - name: product_id
        data_type: text
        description: "Same value as product_id in the dim_products table, linking to the product involved in the opportunity."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_id

      - name: account_id
        data_type: text
        description: "Same value as account_id in the dim_accounts table, linking to the customer account associated with the opportunity."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_accounts')
                field: account_id

      - name: deal_stage
        data_type: text
        description: "Current stage of the sales deal in the pipeline filtered to Closed deals only."
        tests:
          - accepted_values:
              arguments:
                values: ['Won', 'Lost']

      - name: engage_date
        data_type: date
        description: "Date when the sales engagement or interaction with the customer began."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_calendar')
                field: date

      - name: close_date
        data_type: date
        description: "Date when the sales deal was officially closed."

      - name: days_closed
        data_type: integer
        description: "Sales cycle length measured in days from engagement to closing of the deal."

      - name: close_value
        data_type: numeric
        description: "Sales value of the closed deal with the selling price agrreed upon."

      - name: sales_price
        data_type: numeric
        description: "Same value as sales_price in the dim_products table, representing the standard price of the product."

      - name: percent_markup
        data_type: double precision
        description: "Percent markup applied to the closed deal calculated as ((close_value - sales_price) / sales_price) * 100."
